[package]
name = "zettacache"
version = "0.1.0"
authors = ["Delphix"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-stream = "0.3.0"
bincode = "1.3.2"
chrono = "0.4"
conv = "0.3.3"
futures = "0.3.13"
futures-core = "0.3.13"
lazy_static = "1.4.0"
libc = "0.2"
log = "0.4"
lz4 = "1.23.2"
metered = "0.8"
more-asserts = "0.2.1"
nix = "0.22.0"
num = "0.4.0"
roaring = "0.7.0"
seahash = "4.1.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1.4", features = ["full"] }
util = { path = "../util" }
