[package]
name = "zfs_object_agent"
version = "0.1.0"
authors = ["Delphix"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = "2"
log = "0.4"
util = { path = "../util" }
zettacache = { path = "../zettacache" }
zettaobject = { path = "../zettaobject" }
