[package]
name = "zoa_test"
version = "0.1.0"
authors = ["Delphix"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "0.3.2"
chrono = "0.4.19"
clap = "2"
futures = "0.3.13"
lazy_static = "1.4.0"
nvpair = { git = "https://github.com/ahrens/rust-libzfs", branch = "work"}
rand = "0.8.3"
rusoto_core = "0.47.0"
rusoto_credential = "0.47.0"
rusoto_s3 = "0.47.0"
rusoto_sts = "0.47.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1.0.64"
tokio = { version = "1.4", features = ["full"] }
zettacache = { path = "../zettacache" }
zettaobject = { path = "../zettaobject" }
